### ISSUE TITLE
Running errors on the main branch

### ISSUE THREAD

**Issue by plpycoin** [ucbepic/docetl#194]
error output:

```bash
> docet-website@0.1.0 build
> next build

  ▲ Next.js 14.2.11
  - Environments: .env.local

   Creating an optimized production build ...

> Build error occurred
Error: Page config in /data/tib/ie/docetl/website/src/app/api/convertDocuments/route.ts is deprecated. Replace `export const config=…` with the following:
Visit https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config for more information.
    at getPageStaticInfo (/data/tib/ie/docetl/website/node_modules/next/dist/build/analysis/get-page-static-info.js:425:27)
    at async getStaticInfoIncludingLayouts (/data/tib/ie/docetl/website/node_modules/next/dist/build/entries.js:108:28)
    at async /data/tib/ie/docetl/website/node_modules/next/dist/build/entries.js:410:32
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async createEntrypoints (/data/tib/ie/docetl/website/node_modules/next/dist/build/entries.js:550:5)
    at async Span.traceAsyncFn (/data/tib/ie/docetl/website/node_modules/next/dist/trace/trace.js:154:20)
    at async webpackBuildImpl (/data/tib/ie/docetl/website/node_modules/next/dist/build/webpack-build/impl.js:104:25)
    at async Object.workerMain (/data/tib/ie/docetl/website/node_modules/next/dist/build/webpack-build/impl.js:330:20) {
  type: 'Error'
}
make: *** [Makefile:42: run-ui] Error 1
```

npm --version
10.9.0

node --version
v18.20.4

**Comment by shreyashankar** [comment]
ah we may have different TS configs...pushing a fix
