### ISSUE TITLE
Path arguments must not be null error

### ISSUE THREAD

**Issue by mystvearn** [ucbepic/docetl#238]
![image](https://github.com/user-attachments/assets/413cba1a-c029-4dda-b5a5-49e210ea5cd6)

I could successfully built the docker image but the following results appear when I click Run in Playground. Here are contents of my .env and .env.local

**.env (at root folder)**
```
OPENAI_API_KEY=sk-proj-gB5C2t...BdjwT3Blb...
BACKEND_ALLOW_ORIGINS=
BACKEND_HOST=localhost
BACKEND_PORT=8000
BACKEND_RELOAD=True
FRONTEND_HOST=localhost
FRONTEND_PORT=3000
```

**.env.local (in website folder)**
```
OPENAI_API_KEY=sk-proj-gB5C2t...BdjwT3Blb...
OPENAI_API_BASE=https://api.openai.com/v1
MODEL_NAME=gpt-4o-mini

NEXT_PUBLIC_BACKEND_HOST=localhost
NEXT_PUBLIC_BACKEND_PORT=8000
```

Here is the log in console:

```
Pipeline configuration error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at Object.join (node:path:1251:7)
    at a (/app/website/.next/server/app/api/writePipelineConfig/route.js:1:4230)
    at g (/app/website/.next/server/app/api/writePipelineConfig/route.js:1:1140)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/website/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36934
    at async eC.execute (/app/website/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)
    at async eC.handle (/app/website/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38268)
    at async doRender (/app/website/node_modules/next/dist/server/base-server.js:1359:42)
    at async cacheEntry.responseCache.get.routeKind (/app/website/node_modules/next/dist/server/base-server.js:1581:28)
    at async NextNodeServer.renderToResponseWithComponentsImpl (/app/website/node_modules/next/dist/server/base-server.js:1489:28) {
  code: 'ERR_INVALID_ARG_TYPE'
```

**Comment by mystvearn** [comment]
I checked the log. The problem could be with setting localStorage key called docetl_namespace. The value has alwasy been null where I create or set namespace to existing one

**Comment by shreyashankar** [comment]
Thanks for opening the issue, and sorry about the multiple issues!

From your screenshot, I wonder if there's an inconsistent rebase somewhere. The namespace looks empty (the parentheses next to the DocETL logo are empty). If you rebase with main and reload the screen, you should be able to set the namespace as in the edit menu in the screenshot below:

<img width="1723" alt="Screenshot 2024-12-10 at 8 21 39 AM" src="https://github.com/user-attachments/assets/e9fbe861-b1d4-4436-b8ed-008248691522">

And it will open a dialog that looks like this:

<img width="1706" alt="Screenshot 2024-12-10 at 8 25 14 AM" src="https://github.com/user-attachments/assets/24bfd1ca-29a9-4e75-8306-5dbcd4e9c4a9">

Let me know if that does not work for you. Thank you 🙏🏽

**Comment by shreyashankar** [comment]
I'll also make a PR that forces you to set a namespace; as I realize that it's possible to click on the X button on in the dialog and have a null namespace as a result.

**Comment by mystvearn** [comment]
After rebase I can set namespace and as well as running execution sucessfully. However, the following error occurs a few second after the execution. The console is still up for a while before this happens

![image](https://github.com/user-attachments/assets/97ba96d5-3cf4-4fed-b41c-6fbd9a0c338e)

**Comment by shreyashankar** [comment]
i'm realizing there is still that mismatch between dev & prod namespace setting...i have a final today but will debug it in an hour! will keep you posted. thanks for your patience!

**Comment by mystvearn** [comment]
@shreyashankar I hope everything went well with your final. I will retry with a fresh installation now.

**Comment by shreyashankar** [comment]
Thank you! How did it go?

**Comment by shreyashankar** [comment]
Closing due to inactivity
